# Generated by Django 2.2 on 2019-09-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('other', 'Other'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('beauty', 'Beauty')], default='other', max_length=30, verbose_name='Category')),
                ('count', models.FloatField(verbose_name='Count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
            ],
        ),
    ]
